#!/usr/bin/env/python3

string="CCTATGGAACGACGTAGCAGCTACCATTTGGCATTTTCAGTAGGTAGAAACCCGCAACCTCAGCCTGGGTGGGGTCATGTAATAAATTCAGTTATGGAGGGGTTGATGCTTAAAATTGAAACACTTGGCCATGCTTCTAGTCTGAGGCAAAAACCCTTTCTTGGCCGATGCTAACTGAAACATGTATCAAAACGACGGCGCACAATGTGCTTTGCCACAGACTAATCCCGGGCAATTCTCTAAACAATAGACTCAATTTTTGCTAGTACCACCAAAAGCTGAGTTGTTAGAAGACCAACATACCCTCGCTTCTGCCTCCCTATACACTCACCGGATTATCTCCATACCACGAATGACGTGCGGGCTAAGACGATATTGTATCTGACGCATCAATTGCAAATCGTCTAAGCTATAGTCGATAGCGTTGTGCATCGTGATCGGGGTGCAGTCAACCAAGTTTGTGGCCCGTTTATTATACCATACACCAGGCCTTATAACCGACTCCCTGAGGCAAGTCGAGCACCTCCCGTTAGCTCATGGTACATCGTTTCTCGGTTGTTTCGGCCACACGACACGTCCCGTCAGCGTCTACATGGCGTACTTTGCTTTTACGAGAGGCTGAATACGCATCAGTTTGCACGTTGTTGATAGAAACATCGCATCAATGCCTGAGCACTCGCGGTTCAAAGGCGCATAGATTTCAGATTAGAGCCCGAAGCCGGTTACCGGCGGCAATTTGGGCTGACAGGGCGTCGTTGTTCAAGACTTATCGTCGGAACCAATGTGGTTCTGTGCGACTGCGTGAGTTGGTCCGGAAATTTCCACTTGAGTGGTGTGCTCGCAAAACCCCTCTGTACGATGATAATGTATCTT"
string1 = string.replace("A","a")
string2 = string1.replace("T", "t")
string3 = string2.replace("a", "T")
string4 = string3.replace("t", "A")
string5 = string4.replace("G", "g")
string6 = string5.replace("C", "c")
string7 = string6.replace("g","C")
string8 = string7.replace("c","G")
string9 = string8[::-1]

print(string9)